# Generated by Django 5.1.1 on 2024-10-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='auction/media/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_color', models.CharField(default='#ffffff', max_length=7)),
                ('owner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner1', to='auction.owner')),
                ('owner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner2', to='auction.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_price', models.IntegerField(blank=True, null=True)),
                ('base_price', models.IntegerField()),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.playertype')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.team')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidder_name', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.team')),
            ],
        ),
    ]
